server.port=8081
server.servlet.context-path=/ohm_project

spring.datasource.url=jdbc:mysql://localhost:3306/ohm_project
spring.datasource.username=root
spring.datasource.password=trungnhanC2@

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true